### ISSUE TITLE
fix  ERROR  Command "preset" is not defined.  

### ISSUE THREAD

**Issue by fabiopacifici** [fabiopacificicom/laravel-9-preset#1]
After installing the composer package the command was not registered in the Laravel app.

**Comment by fabiopacifici** [comment]
This can be fixed temporary by manually registering the command in the app/Console/Kernel.php, add this protected property that references the command

` protected $commands = [
        \PacificDev\Laravel9Preset\Commands\Preset::class,
    ];`

**Comment by DonnieRich** [comment]
I'm not 100% sure, but seems like in `composer.json` a property is missing.

Current version:
`
 "extra": {
    "providers" : ["PacificDev\\Laravel9Preset\\PacificDevServiceProvider"]
}
`

should be replaced by:
`
 "extra": {
    "laravel": {
        "providers" : ["PacificDev\\Laravel9Preset\\PacificDevServiceProvider"]
    }
}
`

**Comment by fabiopacifici** [comment]
Pull request merged, error fixed! Thanks @DonnieRich
