### ISSUE TITLE
fix the package.json file that is entirely replaced by the stub

### ISSUE THREAD

**Issue by fabiopacifici** [fabiopacificicom/laravel-9-preset#2]
When the command is executed, the package.json file is completely replaced. 
This might cause unintended problems with future Laravel releases. 
We need to update only dependencies added by the package and not the entire file.  

See how this was done in the laravel/ui package's `Preset` class at the following link 
https://github.com/laravel/ui/blob/4.x/src/Presets/Preset.php

**Comment by DonnieRich** [comment]
Tried a fix based on the Preset you linked. It's not perfect, but it should work better now.
